"""Evaluate an ablation on fork states generated by a fixed baseline policy."""

from __future__ import annotations

import argparse
import hashlib
import json
from dataclasses import replace
from pathlib import Path

import torch

from artifacts.localize_counterfactual import load_models
from artifacts.localize_counterfactual_interaction import conditional_auc
from d4mj.counterfactual import OutcomeForks, outcome_metrics
from d4mj.data import patchify
from d4mj.env import reset, step as env_step
from d4mj.transition import advance, observe

ARMS = tuple(
    f"{transition}-{mixer}"
    for transition in ("flow", "direct")
    for mixer in ("attention", "mamba")
)


def arm_config(base: Config, arm: str) -> Config:
    transition, mixer = arm.split("-", 1)
    return replace(base, transition=transition, time_mixer=mixer)


def _digest(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _expect(logits: torch.Tensor, centers: torch.Tensor) -> torch.Tensor:
    mean = (logits.softmax(-1) * centers).sum(-1)
    return mean.sign() * torch.expm1(mean.abs())


def _interaction_auc(score: torch.Tensor, target: torch.Tensor, actions: torch.Tensor):
    """The within-action statistic is undefined if no action has both labels."""
    try:
        return conditional_auc(score, target, actions)
    except RuntimeError as error:
        if "both fatal and safe outcomes" not in str(error):
            raise
        return None


@torch.no_grad()
def evaluate(
    saved,
    encoder,
    trajectory_world,
    trajectory_heads,
    world,
    heads,
    trajectory_config,
    evaluation_config,
):
    if trajectory_config.device != evaluation_config.device:
        raise ValueError("trajectory and evaluation arms must use one device")
    if trajectory_config.n_actions != evaluation_config.n_actions:
        raise ValueError("trajectory and evaluation arms disagree on the action space")
    device = evaluation_config.device
    keys = {
        (int(seed), int(step)): row
        for row, (seed, step) in enumerate(zip(saved["seed"], saved["step"]))
    }
    if len(keys) != len(saved["seed"]):
        raise RuntimeError("saved forks contain duplicate (seed, step) rows")

    by_seed: dict[int, set[int]] = {}
    for seed, step in keys:
        by_seed.setdefault(seed, set()).add(step)

    agents, true_rewards, true_deaths = [], [], []
    model_rewards, model_deaths = [], []
    observed_rewards, observed_deaths = [], []
    seeds, steps = [], []
    reproduced = set()

    for seed in sorted(by_seed):
        wanted = by_seed[seed]
        last = max(wanted)
        observation, env_state = reset(seed)
        trajectory_state = evaluation_state = None
        incoming = torch.full(
            (1, 1), evaluation_config.n_actions, dtype=torch.long, device=device
        )
        trajectory_rng = torch.Generator(device=device).manual_seed(seed + 2**21)
        evaluation_rng = torch.Generator(device=device).manual_seed(seed + 2**21)
        policy_rng = torch.Generator(device=device).manual_seed(seed + 2**20)

        for index in range(last + 1):
            patches = patchify(observation[None, None], evaluation_config.patch).to(device)
            trajectory_state, trajectory_agent = observe(
                trajectory_world,
                encoder,
                trajectory_state,
                incoming,
                patches,
                trajectory_rng,
                trajectory_config,
            )
            evaluation_state, evaluation_agent = observe(
                world,
                encoder,
                evaluation_state,
                incoming,
                patches,
                evaluation_rng,
                evaluation_config,
            )

            key = (seed, index)
            if key in keys:
                row = keys[key]
                row_reward, row_death = [], []
                row_model_reward, row_model_death = [], []
                row_observed_reward, row_observed_death = [], []

                for action in range(evaluation_config.n_actions):
                    successor, _, reward, terminated, _ = env_step(
                        env_state, action, seed + index + 1
                    )
                    if float(reward) != float(saved["true_reward"][row, action]):
                        raise AssertionError(
                            f"reward replay mismatch seed={seed} step={index} action={action}"
                        )
                    if bool(terminated) != bool(saved["true_death"][row, action]):
                        raise AssertionError(
                            f"death replay mismatch seed={seed} step={index} action={action}"
                        )

                    chosen = torch.tensor([[action]], device=device)
                    successor_patches = patchify(
                        successor[None, None], evaluation_config.patch
                    ).to(device)
                    samples = (
                        evaluation_config.outcome_gate_flow_samples
                        if evaluation_config.transition == "flow"
                        else 1
                    )
                    generated_rewards, generated_deaths = [], []
                    observed_rewards_for_action, observed_deaths_for_action = [], []
                    for sample in range(samples):
                        generated_rng = torch.Generator(device=device).manual_seed(
                            evaluation_config.seed
                            + 2**23
                            + seed * 4099
                            + index * 17
                            + sample
                        )
                        _, generated_agent = advance(
                            world,
                            evaluation_state.world,
                            chosen,
                            generated_rng,
                            evaluation_config,
                        )
                        generated = heads(generated_agent)
                        generated_rewards.append(
                            _expect(generated["reward"][:, -1, 0], heads.centers)[0]
                        )
                        generated_deaths.append(
                            1.0 - generated["continuation"][:, -1, 0].sigmoid()[0]
                        )

                        observed_rng = torch.Generator(device=device).manual_seed(
                            evaluation_config.seed
                            + 2**24
                            + seed * 4099
                            + index * 17
                            + sample
                        )
                        _, observed_agent = observe(
                            world,
                            encoder,
                            evaluation_state,
                            chosen,
                            successor_patches,
                            observed_rng,
                            evaluation_config,
                        )
                        observed = heads(observed_agent)
                        observed_rewards_for_action.append(
                            _expect(observed["reward"][:, -1, 0], heads.centers)[0]
                        )
                        observed_deaths_for_action.append(
                            1.0 - observed["continuation"][:, -1, 0].sigmoid()[0]
                        )

                    row_reward.append(float(reward))
                    row_death.append(bool(terminated))
                    row_model_reward.append(float(torch.stack(generated_rewards).mean()))
                    row_model_death.append(float(torch.stack(generated_deaths).mean()))
                    row_observed_reward.append(
                        float(torch.stack(observed_rewards_for_action).mean())
                    )
                    row_observed_death.append(
                        float(torch.stack(observed_deaths_for_action).mean())
                    )

                agents.append(evaluation_agent[0, -1].cpu())
                true_rewards.append(torch.tensor(row_reward))
                true_deaths.append(torch.tensor(row_death))
                model_rewards.append(torch.tensor(row_model_reward))
                model_deaths.append(torch.tensor(row_model_death))
                observed_rewards.append(torch.tensor(row_observed_reward))
                observed_deaths.append(torch.tensor(row_observed_death))
                seeds.append(seed)
                steps.append(index)
                reproduced.add(key)

            logits = trajectory_heads(trajectory_agent)["policy"][:, -1, 0]
            action = int(
                torch.multinomial(logits.softmax(-1), 1, generator=policy_rng)
            )
            observation, env_state, _, terminated, truncated = env_step(
                env_state, action, seed + index + 1
            )
            incoming.fill_(action)
            if terminated or truncated:
                if index < last:
                    missing = sorted(step for step in wanted if step > index)
                    raise RuntimeError(
                        f"baseline trajectory ended before saved steps: {seed=} {missing=}"
                    )
                break

    missing = sorted(set(keys) - reproduced)
    if missing:
        raise RuntimeError(f"failed to reproduce saved fork states: {missing}")

    forks = OutcomeForks(
        agent=torch.stack(agents),
        true_reward=torch.stack(true_rewards),
        true_death=torch.stack(true_deaths),
        model_reward=torch.stack(model_rewards),
        model_death=torch.stack(model_deaths),
        seed=torch.tensor(seeds),
        step=torch.tensor(steps),
        observed_reward=torch.stack(observed_rewards),
        observed_death=torch.stack(observed_deaths),
    )
    return forks


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase1a", type=Path, required=True)
    parser.add_argument("--trajectory-phase2", type=Path, required=True)
    parser.add_argument("--eval-phase2", type=Path, required=True)
    parser.add_argument("--trajectory-arm", choices=ARMS, default="direct-attention")
    parser.add_argument("--eval-arm", choices=ARMS, required=True)
    parser.add_argument("--forks", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()

    from d4mj.config import Config

    base = Config()
    trajectory_config = arm_config(base, args.trajectory_arm)
    evaluation_config = arm_config(base, args.eval_arm)
    encoder, trajectory_world, trajectory_heads = load_models(
        args.phase1a, args.trajectory_phase2, base, trajectory_config
    )
    _, world, heads = load_models(
        args.phase1a, args.eval_phase2, base, evaluation_config
    )
    saved = torch.load(args.forks, weights_only=False)
    forks = evaluate(
        saved,
        encoder,
        trajectory_world,
        trajectory_heads,
        world,
        heads,
        trajectory_config,
        evaluation_config,
    )
    metrics = outcome_metrics(forks, heads, evaluation_config)
    varies = forks.true_death.any(1) & (~forks.true_death).any(1)
    action_ids = torch.arange(evaluation_config.n_actions).expand(int(varies.sum()), -1)
    interaction = {
        "generated": _interaction_auc(
            forks.model_death[varies],
            forks.true_death[varies],
            action_ids,
        ),
        "observed": _interaction_auc(
            forks.observed_death[varies],
            forks.true_death[varies],
            action_ids,
        ),
    }
    args.out_dir.mkdir(parents=True, exist_ok=True)
    torch.save(vars(forks), args.out_dir / "matched.outcome_forks.pt")
    report = {
        "contract": {
            "trajectory_policy": str(args.trajectory_phase2.resolve()),
            "trajectory_arm": args.trajectory_arm,
            "evaluated_model": str(args.eval_phase2.resolve()),
            "evaluated_arm": args.eval_arm,
            "saved_forks": str(args.forks.resolve()),
            "trajectory_phase2_sha256": _digest(args.trajectory_phase2),
            "eval_phase2_sha256": _digest(args.eval_phase2),
            "saved_forks_sha256": _digest(args.forks),
            "truth_replayed_exactly": True,
            "states": int(len(forks.seed)),
            "terminal_opportunity_states": int(varies.sum()),
            "generated_samples_per_action": (
                evaluation_config.outcome_gate_flow_samples
                if evaluation_config.transition == "flow"
                else 1
            ),
        },
        "metrics": metrics,
        "same_action_interaction": interaction,
    }
    (args.out_dir / "matched_report.json").write_text(
        json.dumps(report, indent=2) + "\n"
    )
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
